package platformer.model.effects.particles;

public enum DustType {
    IMPACT,
    RUNNING,
    DASH,
    WALL_SLIDE,
    WALL_JUMP,
    IMPACT_SPARK,
    CRITICAL_HIT,
    PLAYER_HIT,
    SW_TELEPORT,
    SW_CHANNELING_AURA,
    SW_AURA_PULSE,
    SW_AURA_CRACKLE,
    SW_DASH_SLASH,
    JUMP_PAD,
    THUNDERBOLT_AURA,
    HERB_CUT,
    ETHEREAL_DASH,
    RORIC_TELEPORT_OUT,
    RORIC_TELEPORT_IN,
    RORIC_BEAM_CHARGE,
    CELESTIAL_AURA,
    SUMMON_RUPTURE,
    SUMMON_VORTEX
}
