name: CI - Build & Test

on:
  push:
  pull_request:

jobs:
  test-analytics-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests for Analytics Service
        run: |
          cd analytics-service
          chmod +x gradlew
          ./gradlew test