name: CI - Build & Test

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  # This runs on every push to a feature branch
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          'analytics-service',
          'auth-service',
          'game-service',
          'multiplayer-service'
        ]

    name: Unit Test (${{ matrix.service }})

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run unit tests for ${{ matrix.service }}
        run: |
          chmod +x gradlew
          ./gradlew test

  # This only runs for PRs to main.
  integration-tests:
    if: github.event_name == 'pull_request'

    needs: unit-tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['analytics-service', 'auth-service', 'game-service', 'multiplayer-service']

    name: Integration Test (${{ matrix.service }})

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run integration tests for ${{ matrix.service }}
        run: |
          chmod +x gradlew
          ./gradlew integrationTest