name: CI - Build & Test

on:
  push:
  pull_request:

jobs:
  test-services:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - 'analytics-service'
          - 'auth-service'
          - 'game-service'
          - 'multiplayer-service'

    name: test (${{ matrix.service }})

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run tests for ${{ matrix.service }}
        run: |
          chmod +x gradlew
          ./gradlew test